# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Create output directory
      run: mkdir -p /home/bodzio/buildOut/

    - name: Build
      run: go build -o /home/bodzio/buildOut/sales

    - name: Run
      run: go run .

